require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - lib/jekyll-archives.rb

# Remove once Jekyll core has dropped explicit support for Ruby 2.2
Lint/SafeNavigationConsistency:
  Exclude:
    - lib/jekyll-archives/archive.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/LineLength:
  Exclude:
    - lib/jekyll-archives.rb
    - lib/jekyll-archives/archive.rb
    - test/**/*.rb
