#!/bin/bash
set -e

echo "RuboCop $(bundle exec rubocop --version)"
bundle exec rubocop -E --disable-pending-cops $@
success=$?
if ((success != 0)); then
   echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
fi
exit $success
