name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Run Tests (Jekyll ${{ matrix.jekyll_version }}, Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll_version }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "2.7"
          - "3.3"
        jekyll_version:
          - "~> 3.9"
          - "~> 4.0"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Set up ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run Unit Tests
        run: bundle exec rake test

  style_check:
    name: "Style Check (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "3.3"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run RuboCop
        run:  bash script/fmt
